apiVersion: v1
kind: Secret
metadata:
  name: posts-backend-secret
  namespace: posts-app
type: Opaque
stringData:
  MONGO_URI: mongodb://mongo-0.mongo-headless:27017,mongo-1.mongo-headless:27017,mongo-2.mongo-headless:27017/postsdb?replicaSet=rs0
